[window]
startup_mode = "Fullscreen"
decorations = "None"
opacity = 1

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 15.0

[colors]
transparent_background_colors = true
